source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.1'

pod 'AFNetworking'
pod 'Masonry'
pod 'MMPlaceHolder'
pod 'SDWebImage'
pod 'Toast'
pod 'ECSlidingViewController'
pod 'HMSegmentedControl'
pod 'SWTableViewCell'
pod 'REMenu'
pod 'CircleStatus'
pod 'JSONModel'
pod 'MJRefresh'
pod 'BlocksKit'
pod 'EaseMobSDKFull'
pod 'WebViewJavascriptBridge'
pod 'Qiniu'
